export interface ChunkResult {
  chunk_id: string;
  doc_id: string;
  text: string;
  parent_text: string | null;
  source_type: "text" | "audio" | "video" | "scanned";
  language: string;
  collection: string;
  title: string;
  author_speaker: string;
  publisher: string;
  chapter_section: string;
  page_number: number | null;
  timestamp_start: number | null;
  timestamp_end: number | null;
  /** Fully-qualified URL to the original source file. Set at ingestion time. */
  source_url?: string | null;
  /** File extension (pdf, docx, epub, mp3, mp4). Derived from source_url. */
  source_ext?: string | null;
  /** Character offset in rendered HTML companion (for text sources). */
  char_offset?: number | null;
  /** Same passage as `text` but with **bold** Markdown wrapping the
   *  query-relevant spans. Generated by a cheap Gemini Flash Lite pass
   *  in the Convex search action. Optional — falls back to plain `text`. */
  highlighted_text?: string | null;
  /** Which specific query (original or AI-expanded) actually retrieved
   *  this chunk during the cross-query merge. Used for feedback logging
   *  so we can capture training data about which expansions worked. */
  matched_query?: string | null;
}

export interface SearchResult {
  chunk: ChunkResult;
  score: number;
  rerank_score: number | null;
}

export interface SearchResponse {
  results: SearchResult[];
  query: string;
  result_count: number;
  retrieval_time_ms: number;
  /** Alternative Turkish phrasings the search action expanded the user
   *  query into. The fan-out is merged server-side; this list is just
   *  surfaced to the UI so we can show "AI also searched for: …". */
  expanded_queries?: string[];
}

export type AIModel = "gemini" | "claude";
export type SearchMode = "results" | "ai";

export interface AgenticStep {
  query: string;
  resultCount: number;
  reasoning?: string;
}

export interface Message {
  _id: string;
  conversationId: string;
  role: "user" | "assistant";
  content: string;
  model?: AIModel;
  sources?: ChunkResult[];
  isStreaming: boolean;
  /** Per-round agentic search plan. Present iff the assistant ran in
   *  deep-search (agentic) mode. */
  agenticSteps?: AgenticStep[];
  /** Live status string while the agent is searching. Cleared on
   *  finalize. */
  agenticStatus?: string;
  createdAt: number;
}

export interface Conversation {
  _id: string;
  userId: string;
  title: string;
  model: AIModel;
  createdAt: number;
  updatedAt: number;
  isArchived: boolean;
}
