# fly.toml app configuration file generated for hizmetsearch-api on 2026-04-08T12:56:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hizmetsearch-api'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'
  QDRANT_COLLECTION = 'hizmet_rag'
  RAG_API_URL_INTERNAL = 'https://hizmetsearch-api.fly.dev'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
